### ISSUE TITLE
Kiwi Descriptor files for SLES 12 Raspberry Pie 

### ISSUE THREAD

**Issue by arjunm183** [SUSE/kiwi-descriptions#11]
Hello Team,

Is it possible to provide Kiwi Descriptor file for SLES 12 Raspberry Pie .

SUSE has released SLES 12 for ARM (Raspberry Pi)

I would request to let me know if it is possible to get the descriptor file.

Thanks and Regards,
Arjun.M

**Comment by schaefi** [comment]
Hi, sorry for the late response

The problem with SLES or in general enterprise distributions is that we can't provide complete image descriptions because the source repositories are not publicly accessible unless you have a subscription. Thus the user experience is bad and we decided to not host image descriptions for those targets here. I tried with a community variant for sles but that failed, so all pieces in that regard will be deleted from this repository in favour of the community variants e.g leap, centos... etc

Now the situation around image for arm boards is special because every board has its own setup and in some cases also special packages required to make it work. Because of that the arm team at suse has setup an obs project to cover the different boards. You can see this here:

* https://build.opensuse.org/project/subprojects/devel:ARM

Click on "Subprojects" tab and you see a sub project for each board, Rpi included. The project setup builds an image which you can download and test.

I'm afraid but the sle12 target is for the same reason as mentioned above not part of the project list.
But you can take this as a base for sles too

Hope that helps a bit
