### ISSUE TITLE
rhel-07.0-JeOS missing

### ISSUE THREAD

**Issue by dsamx** [SUSE/kiwi-descriptions#36]
An example for RHEL7 is missing; the legacy kiwi had this example:
https://github.com/openSUSE/kiwi/tree/master/template/ix86/rhel-07.0-JeOS
I never got it to work though but that could be me. Maybe an edited copy of the centos version is better.

**Comment by schaefi** [comment]
I haven't added sles, rhel and other enterprise distro example because the repos can't be accessed publicly. I think you should be able to use:

* centos/x86_64/centos-07.0-JeOS

as the base and start with replacing the repos to point to rhel7. I think this should lead you relatively quickly to a successful build.

I would love to add a rhel7 description if we would have access to the repos without an extra subscription. I don't think this is possible ?

**Comment by schaefi** [comment]
> the legacy kiwi had this example:

yes I used a rhel dvd to build this image and find this not very handy

**Comment by schaefi** [comment]
Hope you don't mind, I'm closing this one as the intention with the kiwi-descriptions repo was to provide image descriptions that are open and can be build from public repos. I think we will have that type of problem for any enterprise distro which is why they don't appear here.
