### ISSUE TITLE
The function lookupBiosBootDevice does not do anything

### ISSUE THREAD

**Issue by deacomm** [SUSE/kiwi-descriptions#72]
This functions merely loops over list of found disk devices, but does not really do anything. It should probably be removed.

I'm not even going to mention that if the function actually did anything based on the disk BIOS id that it tries to compare to "0x80", it would break on half the systems, where the hwinfo program simply does not print the "BIOS id:" line.

**Comment by schaefi** [comment]
> This functions merely loops over list of found disk devices, but does not really do anything

it assigns the global variable $bios to the device that has the 0x80 flag set. That variable is used as one matching factor if all others have failed in searchBIOSBootDevice(). I agree with you that all this is not so nice code and there are not many systems that comes with a BIOS that sets the 0x80 flag on the device it got booted from. On the other side it also does not hurt.

All this code in custom_boot/ only exists for compat reasons if people still uses a kiwi initrd instead of dracut. That having said could you explain the circumstances under which you are running into a problem with that code ?

If there is no real issue with it and you are fine to just keep things for compatibility I suggest to not touch it

Thoughts ?

**Comment by deacomm** [comment]
Ah, looks like I missed the $bios variable assignment, sorry.

Anyway, I run into problems with it when booting off a kiwi-built ISO image of SLES15 SP2, and the hwinfo program (called in function lookupDiskDevices) simply does not print the "BIOS id" line, so the variable $diskDevices only contains the actual block devices, instead of alternating block device strings and bios id strings as the function's author intended. This in turn causes the script to loop inside searchBIOSBootDevice function until $try_count reaches 15, and the script exits with a failure.

The problem is not the version of hwinfo program - I have two servers with the same version of hwinfo program installed, but only on one of them the BIOS id line is shown when running "hwinfo --disk". I haven't been able to figure out what causes this.

**Comment by schaefi** [comment]
> Ah, looks like I missed the $bios variable assignment, sorry.

no problem as I said this code is not really nice ;)

> The problem is not the version of hwinfo program - I have two servers with the same version of hwinfo program installed, but only on one of them the BIOS id line is shown when running "hwinfo --disk". I haven't been able to figure out what causes this.

Yes this is "normal" behavior. If you get information at this point or not does not depend on the hwinfo program. It depends on your BIOS implementation. hwinfo sends interrupt-10 and shows what it gets. If the BIOS implementation does not handle the interrupt you don't get any information. This is also the reason why the method searchBIOSBootDevice() uses the int10 info only as the last option if all other attempts to find the device has failed.

I would not spent more time on finding out why hwinfo does not provide bios stored data because you will have a hard time to fix this. I'm more concerned about the other information you provided:

1. You are saying you use this code with sle15. Please note all of that code in custom_boot/... is a legacy code path which we only keep for customers who didn't had a chance to move to dracut as the initrd system. I strongly recommend to not use it if possible because we do not run integration testing of this code for newer systems like sle15

2. As I said the lookup of $bios is a last resort option. Why was the code before not able to identify the boot device ?
    (/var/log/boot.kiwi)

3. Could you explain what image type you are building and maybe some words on your use case ? I'm relatively convinced we can find a solution that prevents you from dealing with bios data

Thanks

**Comment by deacomm** [comment]
We will gladly switch to another, better supported "boot description" (is that the right term in this context?), I would just like to know which one, as the top "suse" directory in this repo does not contain any description for SLES.

We have a need to maintain boot images for recent SLES and RHEL releases. For this we use a slightly dated Kiwi, with several patches applied locally (I think I shared one or two of them here in the past). Some patches are to work around bugs we came across, others are for added customization we need, but is not available through regular configuration, like root LVM logical volume name, or additional GRUB boot options.

`# rpm -q python3-kiwi kiwi-boot-descriptions`
`python3-kiwi-9.17.15-1.6.x86_64`
`kiwi-boot-descriptions-1.1.0-2.11.x86_64`

I'm not sure if this github issue is the right venue for this discussion, as we are getting somewhat off-topic. :)

Anyway, right now I can't reproduce this issue anymore on the same test VM - even after installation finishes, hwinfo *does* show disk BIOS IDs now...

**Comment by deacomm** [comment]
Now I remember - the described issue with lookupBiosBootDevice was nothing more than a dead end in my troubleshooting why a SLES15 SP2 image would not boot, while a SLES15 SP1 image, built from the same configuration had no problems.

The actual issue was that the kernel used with SP2 could not mount devtmpfs to /dev with "nr_inodes=0" (possibly some kind of regression in that kernel, although I haven't had time to look into it further), and so the disk device nodes were not visible inside /dev during installation. After removing that mount option from function createInitialDevices, this got fixed.

So, since my initial assumption that the lookupBiosBootDevice function did not serve any real purpose is wrong, I don't think I should waste more of your time.

I am looking into ditching the old suse-SLES15 description in favour of a dracut-based initrd, and although I am still missing some background info on how it is supposed to work (especially with a LVM-based disk layout), I'm making progress.

Is there some kind of a mailing list or support forum for kiwi, so that we do not have to keep this github issue open?

**Comment by schaefi** [comment]
> I am looking into ditching the old suse-SLES15 description in favour of a dracut-based initrd, and although I am still missing some background info on how it is supposed to work 

we are happy to help with any issue you might have here. If you can share your image description in some way that will speed up the process a lot

> Is there some kind of a mailing list or support forum for kiwi

yep see here:

https://osinside.github.io/kiwi/#contact

We are happy to help

> python3-kiwi-9.17.15-1.6.x86_64

That's relatively old. I suggest using what we have here:

http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/

> kiwi-boot-descriptions-1.1.0-2.11.x86_64

we should aim for deleting this package. Unless you use boot="netboot/
it will not be needed at all once we see and update your XML description :)

Looking forward to meet you on matrix or the mailing list
